namespace Logistics.Domain.Entities.CountryCodesEntity
{
    public class CountryCodes
    {
        public static readonly List<Country> Data = new()
        {
            new Country { Name = "Afghanistan", IsoCode = "AF", DialCode = "+93" },
            new Country { Name = "Albania", IsoCode = "AL", DialCode = "+355" },
            new Country { Name = "Algeria", IsoCode = "DZ", DialCode = "+213" },
            new Country { Name = "Andorra", IsoCode = "AD", DialCode = "+376" },
            new Country { Name = "Angola", IsoCode = "AO", DialCode = "+244" },
            new Country { Name = "Antigua and Barbuda", IsoCode = "AG", DialCode = "+1268" },
            new Country { Name = "Argentina", IsoCode = "AR", DialCode = "+54" },
            new Country { Name = "Armenia", IsoCode = "AM", DialCode = "+374" },
            new Country { Name = "Australia", IsoCode = "AU", DialCode = "+61" },
            new Country { Name = "Austria", IsoCode = "AT", DialCode = "+43" },
            new Country { Name = "Azerbaijan", IsoCode = "AZ", DialCode = "+994" },
            new Country { Name = "Bahamas", IsoCode = "BS", DialCode = "+1242" },
            new Country { Name = "Bahrain", IsoCode = "BH", DialCode = "+973" },
            new Country { Name = "Bangladesh", IsoCode = "BD", DialCode = "+880" },
            new Country { Name = "Barbados", IsoCode = "BB", DialCode = "+1246" },
            new Country { Name = "Belarus", IsoCode = "BY", DialCode = "+375" },
            new Country { Name = "Belgium", IsoCode = "BE", DialCode = "+32" },
            new Country { Name = "Belize", IsoCode = "BZ", DialCode = "+501" },
            new Country { Name = "Benin", IsoCode = "BJ", DialCode = "+229" },
            new Country { Name = "Bhutan", IsoCode = "BT", DialCode = "+975" },
            new Country { Name = "Bolivia", IsoCode = "BO", DialCode = "+591" },
            new Country { Name = "Bosnia and Herzegovina", IsoCode = "BA", DialCode = "+387" },
            new Country { Name = "Botswana", IsoCode = "BW", DialCode = "+267" },
            new Country { Name = "Brazil", IsoCode = "BR", DialCode = "+55" },
            new Country { Name = "Brunei", IsoCode = "BN", DialCode = "+673" },
            new Country { Name = "Bulgaria", IsoCode = "BG", DialCode = "+359" },
            new Country { Name = "Burkina Faso", IsoCode = "BF", DialCode = "+226" },
            new Country { Name = "Burundi", IsoCode = "BI", DialCode = "+257" },
            new Country { Name = "Cabo Verde", IsoCode = "CV", DialCode = "+238" },
            new Country { Name = "Cambodia", IsoCode = "KH", DialCode = "+855" },
            new Country { Name = "Cameroon", IsoCode = "CM", DialCode = "+237" },
            new Country { Name = "Canada", IsoCode = "CA", DialCode = "+1" },
            new Country { Name = "Central African Republic", IsoCode = "CF", DialCode = "+236" },
            new Country { Name = "Chad", IsoCode = "TD", DialCode = "+235" },
            new Country { Name = "Chile", IsoCode = "CL", DialCode = "+56" },
            new Country { Name = "China", IsoCode = "CN", DialCode = "+86" },
            new Country { Name = "Colombia", IsoCode = "CO", DialCode = "+57" },
            new Country { Name = "Comoros", IsoCode = "KM", DialCode = "+269" },
            new Country { Name = "Congo (Congo-Brazzaville)", IsoCode = "CG", DialCode = "+242" },
            new Country { Name = "Congo (DRC)", IsoCode = "CD", DialCode = "+243" },
            new Country { Name = "Costa Rica", IsoCode = "CR", DialCode = "+506" },
            new Country { Name = "Croatia", IsoCode = "HR", DialCode = "+385" },
            new Country { Name = "Cuba", IsoCode = "CU", DialCode = "+53" },
            new Country { Name = "Cyprus", IsoCode = "CY", DialCode = "+357" },
            new Country { Name = "Czechia", IsoCode = "CZ", DialCode = "+420" },
            new Country { Name = "Denmark", IsoCode = "DK", DialCode = "+45" },
            new Country { Name = "Djibouti", IsoCode = "DJ", DialCode = "+253" },
            new Country { Name = "Dominica", IsoCode = "DM", DialCode = "+1767" },
            new Country { Name = "Dominican Republic", IsoCode = "DO", DialCode = "+1809" },
            new Country { Name = "Ecuador", IsoCode = "EC", DialCode = "+593" },
            new Country { Name = "Egypt", IsoCode = "EG", DialCode = "+20" },
            new Country { Name = "El Salvador", IsoCode = "SV", DialCode = "+503" },
            new Country { Name = "Equatorial Guinea", IsoCode = "GQ", DialCode = "+240" },
            new Country { Name = "Eritrea", IsoCode = "ER", DialCode = "+291" },
            new Country { Name = "Estonia", IsoCode = "EE", DialCode = "+372" },
            new Country { Name = "Eswatini", IsoCode = "SZ", DialCode = "+268" },
            new Country { Name = "Ethiopia", IsoCode = "ET", DialCode = "+251" },
            new Country { Name = "Fiji", IsoCode = "FJ", DialCode = "+679" },
            new Country { Name = "Finland", IsoCode = "FI", DialCode = "+358" },
            new Country { Name = "France", IsoCode = "FR", DialCode = "+33" },
            new Country { Name = "Gabon", IsoCode = "GA", DialCode = "+241" },
            new Country { Name = "Gambia", IsoCode = "GM", DialCode = "+220" },
            new Country { Name = "Georgia", IsoCode = "GE", DialCode = "+995" },
            new Country { Name = "Germany", IsoCode = "DE", DialCode = "+49" },
            new Country { Name = "Ghana", IsoCode = "GH", DialCode = "+233" },
            new Country { Name = "Greece", IsoCode = "GR", DialCode = "+30" },
            new Country { Name = "Grenada", IsoCode = "GD", DialCode = "+1473" },
            new Country { Name = "Guatemala", IsoCode = "GT", DialCode = "+502" },
            new Country { Name = "Guinea", IsoCode = "GN", DialCode = "+224" },
            new Country { Name = "Guinea-Bissau", IsoCode = "GW", DialCode = "+245" },
            new Country { Name = "Guyana", IsoCode = "GY", DialCode = "+592" },
            new Country { Name = "Haiti", IsoCode = "HT", DialCode = "+509" },
            new Country { Name = "Honduras", IsoCode = "HN", DialCode = "+504" },
            new Country { Name = "Hungary", IsoCode = "HU", DialCode = "+36" },
            new Country { Name = "Iceland", IsoCode = "IS", DialCode = "+354" },
            new Country { Name = "India", IsoCode = "IN", DialCode = "+91" },
            new Country { Name = "Indonesia", IsoCode = "ID", DialCode = "+62" },
            new Country { Name = "Iran", IsoCode = "IR", DialCode = "+98" },
            new Country { Name = "Iraq", IsoCode = "IQ", DialCode = "+964" },
            new Country { Name = "Ireland", IsoCode = "IE", DialCode = "+353" },
            new Country { Name = "Israel", IsoCode = "IL", DialCode = "+972" },
            new Country { Name = "Italy", IsoCode = "IT", DialCode = "+39" },
            new Country { Name = "Ivory Coast", IsoCode = "CI", DialCode = "+225" },
            new Country { Name = "Jamaica", IsoCode = "JM", DialCode = "+1876" },
            new Country { Name = "Japan", IsoCode = "JP", DialCode = "+81" },
            new Country { Name = "Jordan", IsoCode = "JO", DialCode = "+962" },
            new Country { Name = "Kazakhstan", IsoCode = "KZ", DialCode = "+7" },
            new Country { Name = "Kenya", IsoCode = "KE", DialCode = "+254" },
            new Country { Name = "Kiribati", IsoCode = "KI", DialCode = "+686" },
            new Country { Name = "Kosovo", IsoCode = "XK", DialCode = "+383" },
            new Country { Name = "Kuwait", IsoCode = "KW", DialCode = "+965" },
            new Country { Name = "Kyrgyzstan", IsoCode = "KG", DialCode = "+996" },
            new Country { Name = "Laos", IsoCode = "LA", DialCode = "+856" },
            new Country { Name = "Latvia", IsoCode = "LV", DialCode = "+371" },
            new Country { Name = "Lebanon", IsoCode = "LB", DialCode = "+961" },
            new Country { Name = "Lesotho", IsoCode = "LS", DialCode = "+266" },
            new Country { Name = "Liberia", IsoCode = "LR", DialCode = "+231" },
            new Country { Name = "Libya", IsoCode = "LY", DialCode = "+218" },
            new Country { Name = "Liechtenstein", IsoCode = "LI", DialCode = "+423" },
            new Country { Name = "Lithuania", IsoCode = "LT", DialCode = "+370" },
            new Country { Name = "Luxembourg", IsoCode = "LU", DialCode = "+352" },
            new Country { Name = "Madagascar", IsoCode = "MG", DialCode = "+261" },
            new Country { Name = "Malawi", IsoCode = "MW", DialCode = "+265" },
            new Country { Name = "Malaysia", IsoCode = "MY", DialCode = "+60" },
            new Country { Name = "Maldives", IsoCode = "MV", DialCode = "+960" },
            new Country { Name = "Mali", IsoCode = "ML", DialCode = "+223" },
            new Country { Name = "Malta", IsoCode = "MT", DialCode = "+356" },
            new Country { Name = "Marshall Islands", IsoCode = "MH", DialCode = "+692" },
            new Country { Name = "Mauritania", IsoCode = "MR", DialCode = "+222" },
            new Country { Name = "Mauritius", IsoCode = "MU", DialCode = "+230" },
            new Country { Name = "Mexico", IsoCode = "MX", DialCode = "+52" },
            new Country { Name = "Micronesia", IsoCode = "FM", DialCode = "+691" },
            new Country { Name = "Moldova", IsoCode = "MD", DialCode = "+373" },
            new Country { Name = "Monaco", IsoCode = "MC", DialCode = "+377" },
            new Country { Name = "Mongolia", IsoCode = "MN", DialCode = "+976" },
            new Country { Name = "Montenegro", IsoCode = "ME", DialCode = "+382" },
            new Country { Name = "Morocco", IsoCode = "MA", DialCode = "+212" },
            new Country { Name = "Mozambique", IsoCode = "MZ", DialCode = "+258" },
            new Country { Name = "Myanmar", IsoCode = "MM", DialCode = "+95" },
            new Country { Name = "Namibia", IsoCode = "NA", DialCode = "+264" },
            new Country { Name = "Nauru", IsoCode = "NR", DialCode = "+674" },
            new Country { Name = "Nepal", IsoCode = "NP", DialCode = "+977" },
            new Country { Name = "Netherlands", IsoCode = "NL", DialCode = "+31" },
            new Country { Name = "New Zealand", IsoCode = "NZ", DialCode = "+64" },
            new Country { Name = "Nicaragua", IsoCode = "NI", DialCode = "+505" },
            new Country { Name = "Niger", IsoCode = "NE", DialCode = "+227" },
            new Country { Name = "Nigeria", IsoCode = "NG", DialCode = "+234" },
            new Country { Name = "North Korea", IsoCode = "KP", DialCode = "+850" },
            new Country { Name = "North Macedonia", IsoCode = "MK", DialCode = "+389" },
            new Country { Name = "Norway", IsoCode = "NO", DialCode = "+47" },
            new Country { Name = "Oman", IsoCode = "OM", DialCode = "+968" },
            new Country { Name = "Pakistan", IsoCode = "PK", DialCode = "+92" },
            new Country { Name = "Palau", IsoCode = "PW", DialCode = "+680" },
            new Country { Name = "Palestine", IsoCode = "PS", DialCode = "+970" },
            new Country { Name = "Panama", IsoCode = "PA", DialCode = "+507" },
            new Country { Name = "Papua New Guinea", IsoCode = "PG", DialCode = "+675" },
            new Country { Name = "Paraguay", IsoCode = "PY", DialCode = "+595" },
            new Country { Name = "Peru", IsoCode = "PE", DialCode = "+51" },
            new Country { Name = "Philippines", IsoCode = "PH", DialCode = "+63" },
            new Country { Name = "Poland", IsoCode = "PL", DialCode = "+48" },
            new Country { Name = "Portugal", IsoCode = "PT", DialCode = "+351" },
            new Country { Name = "Qatar", IsoCode = "QA", DialCode = "+974" },
            new Country { Name = "Romania", IsoCode = "RO", DialCode = "+40" },
            new Country { Name = "Russia", IsoCode = "RU", DialCode = "+7" },
            new Country { Name = "Rwanda", IsoCode = "RW", DialCode = "+250" },
            new Country { Name = "Saint Kitts and Nevis", IsoCode = "KN", DialCode = "+1869" },
            new Country { Name = "Saint Lucia", IsoCode = "LC", DialCode = "+1758" },
            new Country { Name = "Saint Vincent and the Grenadines", IsoCode = "VC", DialCode = "+1784" },
            new Country { Name = "Samoa", IsoCode = "WS", DialCode = "+685" },
            new Country { Name = "San Marino", IsoCode = "SM", DialCode = "+378" },
            new Country { Name = "Sao Tome and Principe", IsoCode = "ST", DialCode = "+239" },
            new Country { Name = "Saudi Arabia", IsoCode = "SA", DialCode = "+966" },
            new Country { Name = "Senegal", IsoCode = "SN", DialCode = "+221" },
            new Country { Name = "Serbia", IsoCode = "RS", DialCode = "+381" },
            new Country { Name = "Seychelles", IsoCode = "SC", DialCode = "+248" },
            new Country { Name = "Sierra Leone", IsoCode = "SL", DialCode = "+232" },
            new Country { Name = "Singapore", IsoCode = "SG", DialCode = "+65" },
            new Country { Name = "Slovakia", IsoCode = "SK", DialCode = "+421" },
            new Country { Name = "Slovenia", IsoCode = "SI", DialCode = "+386" },
            new Country { Name = "Solomon Islands", IsoCode = "SB", DialCode = "+677" },
            new Country { Name = "Somalia", IsoCode = "SO", DialCode = "+252" },
            new Country { Name = "South Africa", IsoCode = "ZA", DialCode = "+27" },
            new Country { Name = "South Korea", IsoCode = "KR", DialCode = "+82" },
            new Country { Name = "South Sudan", IsoCode = "SS", DialCode = "+211" },
            new Country { Name = "Spain", IsoCode = "ES", DialCode = "+34" },
            new Country { Name = "Sri Lanka", IsoCode = "LK", DialCode = "+94" },
            new Country { Name = "Sudan", IsoCode = "SD", DialCode = "+249" },
            new Country { Name = "Suriname", IsoCode = "SR", DialCode = "+597" },
            new Country { Name = "Sweden", IsoCode = "SE", DialCode = "+46" },
            new Country { Name = "Switzerland", IsoCode = "CH", DialCode = "+41" },
            new Country { Name = "Syria", IsoCode = "SY", DialCode = "+963" },
            new Country { Name = "Taiwan", IsoCode = "TW", DialCode = "+886" },
            new Country { Name = "Tajikistan", IsoCode = "TJ", DialCode = "+992" },
            new Country { Name = "Tanzania", IsoCode = "TZ", DialCode = "+255" },
            new Country { Name = "Thailand", IsoCode = "TH", DialCode = "+66" },
            new Country { Name = "Timor-Leste", IsoCode = "TL", DialCode = "+670" },
            new Country { Name = "Togo", IsoCode = "TG", DialCode = "+228" },
            new Country { Name = "Tonga", IsoCode = "TO", DialCode = "+676" },
            new Country { Name = "Trinidad and Tobago", IsoCode = "TT", DialCode = "+1868" },
            new Country { Name = "Tunisia", IsoCode = "TN", DialCode = "+216" },
            new Country { Name = "Turkey", IsoCode = "TR", DialCode = "+90" },
            new Country { Name = "Turkmenistan", IsoCode = "TM", DialCode = "+993" },
            new Country { Name = "Tuvalu", IsoCode = "TV", DialCode = "+688" },
            new Country { Name = "Uganda", IsoCode = "UG", DialCode = "+256" },
            new Country { Name = "Ukraine", IsoCode = "UA", DialCode = "+380" },
            new Country { Name = "United Arab Emirates", IsoCode = "AE", DialCode = "+971" },
            new Country { Name = "United Kingdom", IsoCode = "GB", DialCode = "+44" },
            new Country { Name = "United States", IsoCode = "US", DialCode = "+1" },
            new Country { Name = "Uruguay", IsoCode = "UY", DialCode = "+598" },
            new Country { Name = "Uzbekistan", IsoCode = "UZ", DialCode = "+998" },
            new Country { Name = "Vanuatu", IsoCode = "VU", DialCode = "+678" },
            new Country { Name = "Vatican City", IsoCode = "VA", DialCode = "+379" },
            new Country { Name = "Venezuela", IsoCode = "VE", DialCode = "+58" },
            new Country { Name = "Vietnam", IsoCode = "VN", DialCode = "+84" },
            new Country { Name = "Yemen", IsoCode = "YE", DialCode = "+967" },
            new Country { Name = "Zambia", IsoCode = "ZM", DialCode = "+260" },
            new Country { Name = "Zimbabwe", IsoCode = "ZW", DialCode = "+263" },
        };
    }
    public class Country
    {
        public string Name { get; set; } = string.Empty;
        public string IsoCode { get; set; } = string.Empty;
        public string DialCode { get; set; } = string.Empty;
    }
}